spring.application.name=demo
# for https
server.forward-headers-strategy=framework 
# for https
server.forward-headers-strategy=framework
spring.application.name=demo
 
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Tamil2006$
 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
 
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
 
server.port=8080
